### PR TITLE
Sphinx gha

### PR DESCRIPTION
**Pull request by lisajulia**
- Add documentation for the Python bindings from opm-common
- Add documentation for opm_embedded
- Fix typo in docstrings.json from simulators

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this opm-common=4018 please

**Comment by lisajulia** [comment]
@hakonhagland: Can you have a look? Thanks! :)
Then this branch would have to be rebased to opm-simulators master as well.

**Comment by hakonhagland** [comment]
@lisajulia Thanks. I have rebased https://github.com/OPM/opm-simulators/pull/5243. I think it is better if  you submit this PR in the official https://github.com/OPM/opm-simulators/ instead of here in my local fork.

**Comment by lisajulia** [comment]
Ok, I've pushed my commits to your branch :)

**Comment by hakonhagland** [comment]
Thanks, however I think you should a separate pull request for your changes since #5243 is already finished reviewing. And now it will probably become messy if we start reviewing new commits after the review is finished.

**Pull request closed without merging**
